---
title: "ADS - Project 1"
author: "Henrique Saboya Lopes Tavares de Melo (hs2923)"
date: "September 10, 2017"
output: html_document
---

```{r}
library(tm)

#Reading file with speech dates
dates.speeches <- read.table("D:/Google Drive/Google Drive/My Files/2) Estudos/4) Columbia/3) Classes/4) Fall 2017/1) Applied Data Science/1) GitHub/fall2017-project1-hs2923/data/InauguationDates.txt", header = T, skip = 1, sep = "\t")

#Adjusting date formats
for(i in 2:5) {
  dates.speeches[,i] <- as.Date(dates.speeches[,i],"%m/%d/%Y")
}

#Reading Information file 
InaugurationInfo <- read.csv("D:/Google Drive/Google Drive/My Files/2) Estudos/4) Columbia/3) Classes/4) Fall 2017/1) Applied Data Science/1) GitHub/fall2017-project1-hs2923/data/InaugurationInfo.csv")

names(dates.speeches) <- c("President","Date","Date","Date","Date") 
dates.speeches.temp <- dates.speeches[,1:2]
dates.speeches.temp$Term <- rep(1, nrow(dates.speeches.temp))
dates.speeches.temp2 <- dates.speeches[,c(1,3)]
dates.speeches.temp2$Term <- rep(2, nrow(dates.speeches.temp))
dates.speeches.temp <- rbind(dates.speeches.temp, dates.speeches.temp2)

#Adjustments to the dataset
InaugurationInfo[,1] <- as.character(InaugurationInfo[,1]) 
InaugurationInfo[c(25,27),1] <- as.character("Grover Cleveland")
InaugurationInfo[13,1] <- as.character("Martin Van Buren")
InaugurationInfo[c(46,47),1] <- as.character("Richard M. Nixon")

#Dataset Merging
InaugurationInfo <- merge(InaugurationInfo, dates.speeches.temp, all.x = T, all.y = F, by.x = c("President", "Term"), by.y = c("President", "Term"))
rm(dates.speeches.temp, dates.speeches.temp2)


```

Create Corpus

```{r setup, include=FALSE}
directory <- "D:/Google Drive/Google Drive/My Files/2) Estudos/4) Columbia/3) Classes/4) Fall 2017/1) Applied Data Science/1) GitHub/fall2017-project1-hs2923/output/R Notebook/InauguralSpeeches"

doc <- DirSource(directory = directory, encoding = "UTF-8", pattern = "\\.txt$")

ovid <- VCorpus(doc, readerControl = list(language = "en"))
```

Transform Corpus

```{r}
ovid.t <- ovid
ovid.t <- tm_map(ovid.t, content_transformer(tolower))
ovid.t <- tm_map(ovid.t, removeWords, stopwords("english"))
ovid.t <- tm_map(ovid.t, removePunctuation, preserve_intra_word_dashes = T)
ovid.t <- tm_map(ovid.t, stripWhitespace)

```

Who is the most prolix?

```{r}

```

Add information to the documents

```{r}
meta(ovid.t, "Creator") <- InaugurationInfo[,1]
meta(ovid.t, tag = "Term")
```















