---
title: "ADS - Project 1"
author: "Henrique Saboya Lopes Tavares de Melo (hs2923)"
date: "September 10, 2017"
output: html_document
---

```{r}
library(tm)

dates.speeches <- read.table("D:/Google Drive/Google Drive/My Files/2) Estudos/4) Columbia/3) Classes/4) Fall 2017/1) Applied Data Science/1) GitHub/fall2017-project1-hs2923/data/InauguationDates.txt", header = T, skip = 1, sep = "\t")
dates.speeches[,1] <- as.character(dates.speeches[,1])

for(i in 2:5) {
  dates.speeches[,i] <- as.Date(dates.speeches[,i],"%m/%d/%Y")
}

if(dates.speeches[1,3] != "") {
  rbind(dates.speeches, dates.speeches[1,])
}
```

Create Corpus

```{r setup, include=FALSE}
directory <- "D:/Google Drive/Google Drive/My Files/2) Estudos/4) Columbia/3) Classes/4) Fall 2017/1) Applied Data Science/1) GitHub/fall2017-project1-hs2923/output/R Notebook/InauguralSpeeches"

doc <- DirSource(directory = directory, encoding = "UTF-8", pattern = "\\.txt$")

ovid <- VCorpus(doc, readerControl = list(language = "en"))
```

Transform Corpus

```{r}
ovid.t <- ovid
ovid.t <- tm_map(ovid.t, content_transformer(tolower))
ovid.t <- tm_map(ovid.t, removeWords, stopwords("english"))
ovid.t <- tm_map(ovid.t, removePunctuation, preserve_intra_word_dashes = T)
ovid.t <- tm_map(ovid.t, stripWhitespace)

```

Who is the most prolix?

```{r}

```


```{r}

```















